version: '3.4'

services:

  auctionDb:
    image: postgres

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:management

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile


 
  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile

volumes:
  postgres_auction:


