version: '3.4'

services:

  auctionDb:
    container_name: auctionDb 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AuctionDb
    restart: always 
    ports:
      - "5432:5432"
    volumes:
      - postgres_auction:/var/lib/postgresql/data/
 
  
  mongoDb:
    container_name: mongoDb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=admin
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  auctionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=auctionDb;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on: 
      - auctionDb 
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro